INSERT INTO
cards(deck_id, term, definition)
VALUES
(1,'les parties prenantes','stakeholders'),
(1,'faire un retour','give feedback'),
(1,'un raccourci','a shortcut'),
(1,'autant difficile, si difficile','as much as'),
(1,'de plus en plus','more and more'),
(1,'agréable','nice, comfortable'),
(1,'résoudre','to solve'),
(1,'le chemin','the way, the path'),
(1,'la taille','the waist'),
(1,'la banlieue','the suburbs'),
(1,'un endroit','a place'),
(1,'Nulle part','nowhere'),
(1,'se tenir debout','to stand up'),
(1,'autour + de','around smth'),
(1,'durer','to last'),
(1,'changer d''avis','to change their mind'),
(1,'le délai','deadline'),
(1,'irréalisables','unrealistic'),
(1,'il fait doux','mild weather'),
(1,'parmi','among'),
(1,'en bas','downstairs'),
(1,'en haut','upstairs'),
(1,'rire','to laugh'),
(1,'le propriétaire','the owner'),
(1,'le mois précédent','the previous month'),
(1,'le mois prochain','the next month'),
(1,'trier','to sort'),
(1,'pourvoir','to provide'),
(1,'débrouillard','resourceful'),
(1,'avoir recours','resort to, to have need to'),
(1,'agencer','to arrange'),
(1,'un atout','an asset'),
(1,'un rhume','a cold'),
(1,'la gorge','the throat'),
(1,'une tempête de neige','a snow storm'),
(1,'j''ai l''habitude','I''m used to'),
(1,'fêter', 'to celebrate'),
(1,'être agacé','to be annoyed'),
(1,'le voisinage','the neighbourhood'),
(1,'moche','ugly'),
(1,'être doué pour','be good at'),
(1,'les enceintes','the speakers'),
(1,'propre','clean'),
(1,'rangé','tidy'),
(1,'la vitesse','the speed'),
(1,'une hausse','an increase'),
(1,'en baisse','decreasing'),
(1,'réussir','to succeed'),
(1,'hors ligne','offline'),
(1,'soutenir','to support'),
(1,'avoir en tête quelque chose','to have smth in mind'),
(1,'paraître','to look like'),
(1,'avoir lieu','to happen, to take place'),
(1,'Être à l''aise','to be comfortable'),
(1,'éteindre la lumière','to turn off the light'),
(1,'agacer','to annoy'),
(1,'correspondre','to match'),
(1,'venir de','to come from'),
(1,'le divertissement','entertainment'),
(1,'le/la porte-parole','the spokesperson'),
(1,'une subvention','a subsidy'),
(1,'le gaz à effet de serre','greenhouse gas'),
(1,'présentement','currently'),
(1,'le plancher','the floor'),
(1,'ramener','to bring back'),
(1,'être fait main','be handmade'),
(1,'les vaisselle','the dishes'),
(1,'le guichet automatique','the atm'),
(1,'surtout','above all'),
(1,'l''époque actuelle','the current era'),
(1,'coûteux','expensive'),
(1,'bavard','chatty'),
(1,'oser','to dare'),
(1,'deviner','to guess'),
(1,'relacher','to release'),
(1,'sortir des mises a jour','to release updates'),
(1,'gérer des urgences','to handle emergencies'),
(1,'une étape','step, stage'),
(1,'les personnages','the characters'),
(1,'joli(e)','pretty'),
(1,'flemmard','lazy'),
(1,'gentil','nice'),
(1,'méchant','bad, wicked'),
(1,'à l''aise,','at ease'),
(1,'ravi(e)','delighted'),
(1,'Être reconnaissant','to be grateful'),
(1,'le batteur','drummer'),
(1,'le banc','the bench'),
(1,'collation','snack'),
(1,'grignoter','to snack'),
(1,'dessiner','to draw'),
(1,'le stagiaire','the intern'),
(1,'le défi','the challenge'),
(1,'le déroulement','the course'),
(1,'la plainte','the complaint'),
(1,'porter plainte','to complain'),
(1,'pratique','practical'),
(1,'ailleurs','elsewhere'),
(1,'noyer','to drown'),
(1,'essuyer','to wipe'),
(1,'appuyer','to lean on'),
(1, 'déçu', 'disappointed'),
(1,'assez','rather'),
(1, 'mouillé', 'wet'),
(1, 'vague', 'wave'),
(1,'couloir', 'hallway'),
(1,'montre x du doigt',  'point at'),
(1,'ventre', 'stomach'),
(1,'lourd',  'heavy'),
(1,'le paquet', 'package'),
(1,'jeter', 'throw out'),
(1,'le bazar', 'a mess/junk'),
(1,'laisser', 'to leave (tr)'),
(1,'bien s’entendre',  'get along well with'),
(1,'tellement', 'so many'),
(1,'tort', 'wrong'),
(1,'s’habille', 'get dressed'),
(1,'s’allonger', 'lie down'),
(1,'correctement','appropriately'),
(1,'le boulot', 'work'),
(1,'sombre', 'dark'),
(1,'dur','hard'),
(1,'PDG','CEO'),
(1,'emprunter','borrow'),
(1,'l’endroit','place'),
(1,'respecter le délai','to meet the deadline'),
(1,'sortir une application','to release an app'),
(1,'temps supplémentaires','overtime'),
(1,'commandes à emporter','take out (n)'),
(1,'tous les deux','both'),
(1,'beurre d’arachides.','peanut butter'),
(1,'Je m’en suis rendu compte','I realized it'),
(1,'les écouteurs','earphones'),
(1,'rejoindre','to join'),
(1,'avoir des nouvelles','to get some news'),
(1,'Être fier','to be proud'),
(1,'revoir quelqu’un','to see someone again'),
(1,'le centre-ville','downtown'),
(2, 'What is Callback hell?', 'A situation where you have multiple asynchronous functions. Those functions depends on another, so it could get quite messy'),
(2, 'What is the DOM?', 'It represents the page so that programs can change the document structure, style, and content. The DOM represents the document as nodes and objects; that way, programming languages can interact with the page.'),
(2, 'What is the virtual DOM in React?', 'The virtual DOM provides a mechanism that abstracts manual DOM manipulations away from the developer, helping us to write more predictable code.'),
(1, 'un pourboire', 'a tip'),
(1,' tais-toi', 'be quiet'),
(1,'l’eau pétillante', 'sparkling water'),
(1,'cru', 'raw'),
(1,' pourtant', 'yet [connective]'),
(1,'mec', 'a guy'),
(1,'le quai', 'the platform'),
(1,'le moyen', 'the average'),
(1,'le siège', 'the seat'),
(1,'ça s’écrit comment', 'how is that spelled?'),
(1,'en colère', 'angry'),
(1,'une grève', 'a strike'),
(1,'un ouvrier', 'factory worker'),
(1,'une affiche', 'poster'),
(1,'se réunir', 'get together'),
(1,'par terre', 'to the ground'),
(1,'fausse', 'false'),
(1,'un but', 'an objective '),
(1,'la foule', 'the crowd '),
(1,'une crevette', 'a shrimp'),
(1,'la moitié', 'half'),
(1,'entière', 'whole'),
(1,'La canette', 'the can'),
(1,'un loisir', 'a hobby'), 
(1,'la douleur', 'a pain'),
(1,'le cou', 'the neck'),
(1,'la trousse', 'Pencil case'),
(1,'se rappeler', 'remember'),
(1,'un niveau', 'a level'),
(1,'une colline', 'a hill'),
(1,'L’écran', 'the screen '),
(1,'un roux', 'a redhead '),
(1,'châtain', 'light brown haired'),
(1,'le son', 'the sound '),
(1,'dès que', 'as soon as'),
(1,'la morue', 'salted cod'),
(1,'l’eau plate', 'still water'),
(1,'chauve', 'bald'),
(1,'sinon', 'otherwise'),
(1,'atterrir', 'to arrivé to land'),
(1,'décoller', 'to depart, to take off'),
(1,'belle-mère', 'mother-in-law'),
(1,'tricoter', 'to knit '),
(1,'un mensonge', 'a lie'),
(1,'fier', 'proud'),
(1,'un comptable', 'an accountant '),
(1,'au bord de', 'at the edge of'),
(1,'se rendre compte de', 'to realize '),
(1,'un sourire', 'a smile'),
(1,'un mouchoir', 'a tissue '),
(1,'costaud', 'strong'),
(1,'faire d’escalade', 'rock climbing '),
(1,'croisière', 'a cruise '),
(1,'les déchets', 'garbage'),
(1,'se battre', 'to fight'),
(1,'j’ai du mal à', 'i am unsuccessful at'),
(1,'aveugle', 'blind'),
(1,'maigrir', 'to lose weight '),
(1,'sourd', 'deaf'),
(1,'le menton', 'the chin '),
(1,'se raser', 'to shave oneself'),
(1,'faible', 'weak'),
(1,'encore plus', 'even more'),
(1,'sa propre', 'his own'),
(1,'la livraison', 'the delivery'),
(1,'déménager', 'to move [house]'),
(1,'une réussite', 'a success'),
(1,'gêner', 'to bother '),
(1,'amener', 'pick up and drop off'),
(1,'emmener', 'to take and stay with, to bring someone'),
(1,'se trouver', 'be located'),
(1,'le panneau', 'the sign'),
(1,'s’en aller', 'to leave'),
(1,'revenir en arrière', 'go backwards '),
(1,'le piéton', 'the pedestrian'),
(1,'la caisse', 'the cash register '),
(1,'debout', 'standing up'),
(1,'frere aîné', 'older brother '),
(1,'s’entendre bien', 'get along well'),
(1,'Se faire la bise', 'kiss each others cheek'),
(1,'il nous en reste une douzaine', 'we still have a dozen of them '),
(1,'les plats fait maison', 'home made dishes'),
(1,'congeler', 'the freeze'),
(1,'la saveur', 'flavour'),
(1,'un milliard', 'a billion'),
(1,'les années soixante', 'the 60s'),
(1,'ramasser', 'to pick up'),
(1,'imprévus', 'unexpected'),
(1,'un paysage', 'a landscape'),
(1,'angoisse', 'anxious'),
(1,'se taire', 'to be quiet'),
(1,'mal à l’aise', 'uncomfortable'),
(1,'le feu d’artifice', 'fire works'),
(1,'la mairie', 'city hall'),
(1,'un tapis de course', 'a treadmill'),
(1,'un bâtiment', 'a building'), 
(1,'se déplacer- to get around', 'to get from one place to another'),
(1,'La poussière', 'dust'),
(1,'l’évier', 'kitchen sink'),
(1,'le dentifrice', 'toothpaste'),
(1,'un chaton', 'a kitten'),
(1,'une pile', 'a battery'),
(1,'la douane', 'customs [in an airport]'),
(1,'bourdonnement', 'buzzing'),
(1,'me tracasser', 'bother'),
(1,'veuve', 'widow'),
(1,'transpirer', 'sweat'),
(1,'arobase', 'at sign'),
(1,'Avoir du mal à comprendre', 'be confused'),
(1,'coller', 'to paste'),
(1,'les impôts', 'taxes'),
(1,'des plat à emporter', 'some takeout'),
(1,'tout a fait', 'absolutely'),
(1,'emballer', 'wrap'),
(1,'renseignement', 'information'),
(1,'offert ', 'free'),
(1,'Les joues ', 'cheeks'),
(1,'En vedette ', 'features'),
(1,'Verrouille ', 'locked'),
(1,'Empêcher', 'violate or contradict'),
(1,'Fournisseur ', 'provider'),
(1,'Les baleines', 'the whales'),
(1,'serré ', 'tight'),
(1,'Les pois ', 'polka dots '),
(1,'La rayure', 'stripe'),
(1,'ample ', 'loose'),
(1,'argenté', 'silver grey'),
(1,'une manche ', 'sleeve'),
(1,'fourrure', 'fur'),
(1,'soie ', 'silk'),
(1,'le col', 'the collar'),
(1,'a l’envers', 'backwards'),
(1,'un trou ', 'a hole'),
(1,'les collants ', 'tights'),
(1,'une viennoiserie', 'a pastry'),
(1,'amère', 'bitter'),
(1,'les laitues', 'lettuce'),
(1,'acide ', 'sour'),
(1,'la dinde', 'the turkey'),
(1,'plus maintenant ', 'not anymore'),
(1,'déclencher', 'to trigger to launch'),
(1,'Les maquettes ', 'design mocks'),
(1,'dévoiler', 'reveal'),
(1,'Gabarit', 'template'),
(1,'Feuille de route', 'road map route'),
(1,'énervante ', 'annoying '),
(1,'débrancher ', 'unplug'),
(1,'supprimer ', 'delete'),
(1,'surtout ', 'above all'),
(1,'la pièce jointe ', 'attachment'),
(1,'éternuer', 'sneeze'),
(1,'surprenant ', 'unexpected '),
(1,'tout a l’heure ', 'later'),
(1,'Reporter ', 'postpone'),
(1,'se détendre', 'to relax'),
(1,'vrac ', 'bulk'),
(1,'se fasse une tête', 'to get an idea'),
(1,'cibler ', 'to target'),
(1,'interagir ', 'to interact '),
(1,'cadre ', 'frame'),
(1,'libellé', 'wording'),
(1,'Diriger ', 'direct '),
(1,'le balai ', 'broom'),
(1,'la vaisselle ', 'dishes'),
(1,'un aspirateur', 'a vacuum '),
(1,'enlever ', 'remove '),
(1,'l’échelle', 'the ladder'),
(1,'la table de chevet ', 'night stand');