INSERT INTO
cards(deck_id, term, definition)
VALUES
(1,'les parties prenantes','stakeholders'),
(1,'faire un retour','give feedback'),
(1,'un raccourci','a shortcut'),
(1,'autant difficile, si difficile','as much as'),
(1,'de plus en plus','more and more'),
(1,'agréable','nice, comfortable'),
(1,'résoudre','to solve'),
(1,'le chemin','the way, the path'),
(1,'la taille','the waist'),
(1,'la banlieue','the suburbs'),
(1,'un endroit','a place'),
(1,'Nulle part','nowhere'),
(1,'se tenir debout','to stand up'),
(1,'autour + de','around smth'),
(1,'durer','to last'),
(1,'changer d''avis','to change their mind'),
(1,'le délai','deadline'),
(1,'irréalisables','unrealistic'),
(1,'il fait doux','mild weather'),
(1,'parmi','among'),
(1,'en bas','downstairs'),
(1,'en haut','upstairs'),
(1,'rire','to laugh'),
(1,'le propriétaire','the owner'),
(1,'le mois précédent','the previous month'),
(1,'le mois prochain','the next month'),
(1,'trier','to sort'),
(1,'pourvoir','to provide'),
(1,'débrouillard','resourceful'),
(1,'avoir recours','resort to, to have need to'),
(1,'agencer','to arrange'),
(1,'un atout','an asset'),
(1,'un rhume','a cold'),
(1,'la gorge','the throat'),
(1,'une tempête de neige','a snow storm'),
(1,'j''ai l''habitude','I''m used to'),
(1,'fêter', 'to celebrate'),
(1,'être agacé','to be annoyed'),
(1,'le voisinage','the neighbourhood'),
(1,'moche','ugy'),
(1,'être doué pour','be good at'),
(1,'les enceintes','the speakers'),
(1,'propre','clean'),
(1,'rangé','tidy'),
(1,'la vitesse','the speed'),
(1,'une hausse','an increase'),
(1,'en baisse','decreasing'),
(1,'réussir','to succeed'),
(1,'hors ligne','offline'),
(1,'soutenir','to support'),
(1,'avoir en tête quelque chose','to have smth in mind'),
(1,'paraître','to look like'),
(1,'avoir lieu','to happen, to take place'),
(1,'Être à l''aise','to be comfortable'),
(1,'éteindre la lumière','to turn off the light'),
(1,'agacer','to annoy'),
(1,'correspondre','to match'),
(1,'venir de','to come from'),
(1,'le divertissement','entertainment'),
(1,'le/la porte-parole','the spokesperson'),
(1,'une subvention','a subsidy'),
(1,'le gaz à effet de serre','greenhouse gas'),
(1,'présentement','currently'),
(1,'le plancher','the floor'),
(1,'ramener','to bring back'),
(1,'être fait main','be handmade'),
(1,'les vaisselle','the dishes'),
(1,'le guichet automatique','the atm'),
(1,'surtout','above all'),
(1,'l''époque actuelle','the current era'),
(1,'coûteux','expensive'),
(1,'bavard','chatty'),
(1,'oser','to dare'),
(1,'deviner','to guess'),
(1,'relacher','to release'),
(1,'sortir des mises a jour','to release updates'),
(1,'gérer des urgences','to handle emergencies'),
(1,'une étape','step, stage'),
(1,'les personnages','the characters'),
(1,'joli(e)','pretty'),
(1,'flemmard','lazy'),
(1,'gentil','nice'),
(1,'méchant','bad, wicked'),
(1,'à l''aise,','at ease'),
(1,'ravi(e)','delighted'),
(1,'Être reconnaissant','to be grateful'),
(1,'le batteur','drummer'),
(1,'le banc','the bench'),
(1,'collation','snack'),
(1,'grignoter','to snack'),
(1,'dessiner','to draw'),
(1,'le stagiaire','the intern'),
(1,'le défi','the challenge'),
(1,'le déroulement','the course'),
(1,'la plainte','the complaint'),
(1,'porter plainte','to complain'),
(1,'pratique','practical'),
(1,'ailleurs','elsewhere'),
(1,'noyer','to drown'),
(1,'essuyer','to wipe'),
(1,'appuyer','to lean on'),
(2, 'What is Callback hell?', 'A situation where you have multiple asynchronous functions. Those functions depends on another, so it could get quite messy');