DROP TABLE IF EXISTS cards CASCADE;
CREATE TABLE "cards" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "deck_id" Integer NOT NULL,
  "term" VARCHAR(500) NOT NULL,
  "definition" VARCHAR(500) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);